---
###############################################################################
#
# container_started.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - podman_container_record is defined
    fail_msg: "All tests did not pass"

###############################################################################
# ENSURING CONTAINER IS STARTED
###############################################################################

- name: "Checking container status"
  ansible.builtin.command: podman inspect --format '{{ "{{ .State.Status }}" }}' {{ podman_container_record.parameters.name }}
  register: container_active
  changed_when: false
  failed_when: false

- name: "Ensuring container is started"
  ansible.builtin.shell: >
    podman start {{ podman_container_record.parameters.name }}
  changed_when: true
  when: container_active.stdout != "running"
