---
###############################################################################
#
# main.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# CHECKING REQUIREMENTS
###############################################################################

- name: "Checking if we are in container"
  ansible.builtin.meta: end_play
  when: ansible_virtualization_type in ["docker", "podman", "lxc"]

- name: "Checking if operating system is supported"
  ansible.builtin.fail:
    msg: "Unsupported operating system: {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
  when: >
    iac_supported_os | selectattr('name', 'equalto', ansible_distribution)
                     | selectattr('versions', 'contains', ansible_distribution_major_version)
                     | list
                     | length == 0

- name: "Checking if service_key is found from variables"
  ansible.builtin.fail:
    msg: "iac_blueprint or iac_blueprint.podman is not defined"
  when:
    - iac_blueprint is not defined
    - iac_blueprint.podman is not defined

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Setting what containers are to be configured"
  ansible.builtin.set_fact:
    podman_containers: "{{ iac_blueprint.podman.containers }}"
    podman_network_configuration: "{{ iac_blueprint.podman.configuration.network }}"

- name: "Checking proxy address if it's defined"
  ansible.builtin.set_fact:
    proxy_host: "{{ (http_proxy | regex_replace('^https?://', '')).split(':')[0] }}"
    proxy_port: "{{ (http_proxy | regex_replace('^https?://', '')).split(':')[1] | int }}"
  when: >
    (
      (http_proxy is defined and http_proxy != "")
      or (https_proxy is defined and https_proxy != "")
    )
    and (inventory_hostname not in (no_proxy | default("") | split(",")))

- name: "Checking that proxy connection is working if it's defined"
  ansible.builtin.wait_for:
    host: "{{ proxy_host }}"
    port: "{{ proxy_port }}"
    state: "started"
    timeout: 3
  when: >
    (
      (http_proxy is defined and http_proxy != "")
      or (https_proxy is defined and https_proxy != "")
    )
    and (inventory_hostname not in (no_proxy | default("") | split(",")))

###############################################################################
# CHECKING STATES
###############################################################################

- name: "STATE: Ensure all installation is done"
  ansible.builtin.include_tasks: install.yml
  when: state == 'install'

- name: "STATE: Ensure all installation is gone"
  ansible.builtin.include_tasks: uninstall.yml
  when: state == 'uninstall'

- name: "STATE: Ensure Podman installation is present"
  ansible.builtin.include_tasks: present.yml
  when: state == 'present'

- name: "STATE: Ensure Podman installation is absent"
  ansible.builtin.include_tasks: absent.yml
  when: state == 'absent'

- name: "STATE: Ensure container is present"
  ansible.builtin.include_tasks: loop_containers.yml
  vars:
    task_state: "container_present"
  when: state == 'container_present'

- name: "STATE: Ensure container is absent"
  ansible.builtin.include_tasks: loop_containers.yml
  vars:
    task_state: "container_absent"
  when: state == 'container_absent'

- name: "STATE: Ensure container is present"
  ansible.builtin.include_tasks: loop_containers.yml
  vars:
    task_state: "container_started"
  when: state == 'container_started'

- name: "STATE: Ensure container is absent"
  ansible.builtin.include_tasks: loop_containers.yml
  vars:
    task_state: "container_stopped"
  when: state == 'container_stopped'
